### ISSUE TITLE
What's the meaning of each input dimention?

### ISSUE THREAD

**Issue by Riqzz** [Luoxd1996/Active_Contour_Euler_Elastica_Loss#1]
Hello, I want to test the performance of this loss function on other dataset. Coud you explain the meaning of each input dimention in the demo? 

```python
x2 = torch.rand((2, 3, 97, 80))
x3 = torch.rand((2, 4, 112, 97, 80))
```

**Comment by Luoxd1996** [comment]
Same with the input of CE and DICE Loss.
