### ISSUE TITLE
Thanks for your contribution

### ISSUE THREAD

**Issue by AlphaJia** [Luoxd1996/Active_Contour_Euler_Elastica_Loss#2]
Good Jod! I tried to use the 3D ACE loss in my project, focusing on 3D vessel segmentation! 
Also great job and thanks for PyMIC Repo!
You can also ensemble 3D ACE loss in PyMIC, just my advice!

**Comment by Luoxd1996** [comment]
Hi, Jia, 
Thanks for your instructive suggestion, it's easy to add the ACELoss into the PyMIC,  you just need to copy the code and add it to the loss dictionary, in the future, maybe we will merge them.
Best,
Xiangde.
